Script started on 2016年03月02日 (週三) 17時38分29秒
]0;F74046284@2015cpp: ~[01;32mF74046284@2015cpp[00m:[01;34m~[00m$ ls
lab1.script
]0;F74046284@2015cpp: ~[01;32mF74046284@2015cpp[00m:[01;34m~[00m$ whoami;pwd
F74046284
/home/F74046284
]0;F74046284@2015cpp: ~[01;32mF74046284@2015cpp[00m:[01;34m~[00m$ git config -l
]0;F74046284@2015cpp: ~[01;32mF74046284@2015cpp[00m:[01;34m~[00m$ git config -l[Kl[K[K-- [Kglobal [K]0;F74046284@2015cpp: ~[01;32mF74046284@2015cpp[00m:[01;34m~[00m$ git config --global user,[K.name""[K[K ""a"b"e"n"2"0"8"0"7"[C
]0;F74046284@2015cpp: ~[01;32mF74046284@2015cpp[00m:[01;34m~[00m$ git config --global user.name "aben20807"[1P "aben20807"[1P "aben20807"[1P "aben20807"[1P "aben20807"e "aben20807"m "aben20807"a "aben20807"i "aben20807"l "aben20807"[C[C[C[C[C[C[C[C[C[C[C@"g"m"a"i"l"."c"o"m" [A]0;F74046284@2015cpp: ~[01;32mF74046284@2015cpp[00m:[01;34m~[00m$ [C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C
[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C
[K[A]0;F74046284@2015cpp: ~[01;32mF74046284@2015cpp[00m:[01;34m~[00m$ git config --global user.email "aben20807@gmail.com"[C
]0;F74046284@2015cpp: ~[01;32mF74046284@2015cpp[00m:[01;34m~[00m$ git config --global user.email "aben20807@gmail.com"[11Pname "aben20807"l[K
user.name=aben20807
user.email=aben20807@gmail.com
]0;F74046284@2015cpp: ~[01;32mF74046284@2015cpp[00m:[01;34m~[00m$ git clone https://github.com/aben20807/lab1.git
Cloning into 'lab1'...
remote: Counting objects: 3, done.[K
remote: Compressing objects:  50% (1/2)   [Kremote: Compressing objects: 100% (2/2)   [Kremote: Compressing objects: 100% (2/2), done.[K
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0[K
Unpacking objects:  33% (1/3)   Unpacking objects:  66% (2/3)   Unpacking objects: 100% (3/3)   Unpacking objects: 100% (3/3), done.
]0;F74046284@2015cpp: ~[01;32mF74046284@2015cpp[00m:[01;34m~[00m$ exit

Script done on 2016年03月02日 (週三) 17時42分21秒
